# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.tienda_pb2 as tienda__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x1a\x0ctienda.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x05Stock\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x17\n\x06tienda\x18\x02 \x01(\x0b\x32\x07.Tienda\x12\x17\n\x0fproducto_codigo\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\"\x1c\n\x0eStockIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"#\n\tStockList\x12\x16\n\x06stocks\x18\x01 \x03(\x0b\x32\x06.Stock\"2\n\x12StockUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x32\xfb\x01\n\x0cStockService\x12\x15\n\x03\x61\x64\x64\x12\x06.Stock\x1a\x06.Stock\x12%\n\ngetOneById\x12\x0f.StockIdRequest\x1a\x06.Stock\x12,\n\x06getAll\x12\x16.google.protobuf.Empty\x1a\n.StockList\x12\x18\n\x06update\x12\x06.Stock\x1a\x06.Stock\x12\x32\n\x13updateStockQuantity\x12\x13.StockUpdateRequest\x1a\x06.Stock\x12\x31\n\x06\x64\x65lete\x12\x0f.StockIdRequest\x1a\x16.google.protobuf.EmptyB#\n\x1f\x63om.stockearte.tp1_grupo10.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.stockearte.tp1_grupo10.grpcP\001'
  _globals['_STOCK']._serialized_start=58
  _globals['_STOCK']._serialized_end=145
  _globals['_STOCKIDREQUEST']._serialized_start=147
  _globals['_STOCKIDREQUEST']._serialized_end=175
  _globals['_STOCKLIST']._serialized_start=177
  _globals['_STOCKLIST']._serialized_end=212
  _globals['_STOCKUPDATEREQUEST']._serialized_start=214
  _globals['_STOCKUPDATEREQUEST']._serialized_end=264
  _globals['_STOCKSERVICE']._serialized_start=267
  _globals['_STOCKSERVICE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
