# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tienda.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctienda.proto\x1a\x1bgoogle/protobuf/empty.proto\"b\n\x06Tienda\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x11\n\tdireccion\x18\x02 \x01(\t\x12\x0e\n\x06\x63iudad\x18\x03 \x01(\t\x12\x11\n\tprovincia\x18\x04 \x01(\t\x12\x12\n\nhabilitada\x18\x05 \x01(\x08\"!\n\x0fTiendaIdRequest\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"&\n\nTiendaList\x12\x18\n\x07tiendas\x18\x01 \x03(\x0b\x32\x07.Tienda2\x9c\x01\n\rTiendaService\x12\x17\n\x03\x61\x64\x64\x12\x07.Tienda\x1a\x07.Tienda\x12\'\n\ngetOneById\x12\x10.TiendaIdRequest\x1a\x07.Tienda\x12-\n\x06getAll\x12\x16.google.protobuf.Empty\x1a\x0b.TiendaList\x12\x1a\n\x06update\x12\x07.Tienda\x1a\x07.TiendaB#\n\x1f\x63om.stockearte.tp1_grupo10.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tienda_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.stockearte.tp1_grupo10.grpcP\001'
  _globals['_TIENDA']._serialized_start=45
  _globals['_TIENDA']._serialized_end=143
  _globals['_TIENDAIDREQUEST']._serialized_start=145
  _globals['_TIENDAIDREQUEST']._serialized_end=178
  _globals['_TIENDALIST']._serialized_start=180
  _globals['_TIENDALIST']._serialized_end=218
  _globals['_TIENDASERVICE']._serialized_start=221
  _globals['_TIENDASERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
