# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usuario.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.tienda_pb2 as tienda__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\x1a\x0ctienda.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x12\n\ncontrasena\x18\x03 \x01(\t\x12\x17\n\x06tienda\x18\x04 \x01(\x0b\x32\x07.Tienda\x12\x0e\n\x06nombre\x18\x05 \x01(\t\x12\x10\n\x08\x61pellido\x18\x06 \x01(\t\x12\x0b\n\x03rol\x18\x07 \x01(\t\x12\x12\n\nhabilitado\x18\x08 \x01(\x08\"\x1e\n\x10UsuarioIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"@\n\x13UsuarioLoginRequest\x12\x15\n\rnombreUsuario\x18\x01 \x01(\t\x12\x12\n\ncontrasena\x18\x02 \x01(\t\"A\n\x16UsuarioBusquedaRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x17\n\x06tienda\x18\x02 \x01(\x0b\x32\x07.Tienda\")\n\x0bUsuarioList\x12\x1a\n\x08usuarios\x18\x01 \x03(\x0b\x32\x08.Usuario2\x81\x02\n\x0eUsuarioService\x12\x19\n\x03\x61\x64\x64\x12\x08.Usuario\x1a\x08.Usuario\x12)\n\ngetOneById\x12\x11.UsuarioIdRequest\x1a\x08.Usuario\x12.\n\x06getAll\x12\x16.google.protobuf.Empty\x1a\x0c.UsuarioList\x12\x1c\n\x06update\x12\x08.Usuario\x1a\x08.Usuario\x12\'\n\x05login\x12\x14.UsuarioLoginRequest\x1a\x08.Usuario\x12\x32\n\rbuscarUsuario\x12\x17.UsuarioBusquedaRequest\x1a\x08.UsuarioB#\n\x1f\x63om.stockearte.tp1_grupo10.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.stockearte.tp1_grupo10.grpcP\001'
  _globals['_USUARIO']._serialized_start=61
  _globals['_USUARIO']._serialized_end=217
  _globals['_USUARIOIDREQUEST']._serialized_start=219
  _globals['_USUARIOIDREQUEST']._serialized_end=249
  _globals['_USUARIOLOGINREQUEST']._serialized_start=251
  _globals['_USUARIOLOGINREQUEST']._serialized_end=315
  _globals['_USUARIOBUSQUEDAREQUEST']._serialized_start=317
  _globals['_USUARIOBUSQUEDAREQUEST']._serialized_end=382
  _globals['_USUARIOLIST']._serialized_start=384
  _globals['_USUARIOLIST']._serialized_end=425
  _globals['_USUARIOSERVICE']._serialized_start=428
  _globals['_USUARIOSERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
